name: Build & Deploy Dockerize Spring

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Dockerize Spring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'openjdk'

      # ./gradlew -b (batch Mode : means there will be no interactive mode), build.gradle (build file with correct path, its necessary when the build file is not in the root directory), test (gradlew test task name)
      - name: Unit Test
        run: ./gradlew -b build.gradle test

      - name: Build with Gradle
        run: ./gradlew -b build.gradle build

      - name: Build Docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerize-spring:$(date +'%Y-%m-%d-%H-%M-%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerize-spring:$(date +'%Y-%m-%d-%H-%M-%S')

          